### ISSUE TITLE
Highlighting active task/subtask

### ISSUE THREAD

**Issue by Sonderwoods** [procedural-build/ProceduralCS#14]
When editing files, it would be very convenient to highlight in the listview which task/subtask I'm actually editing.
The links in the URL bar uses the GUIDs and can be difficult to read.

![image](https://user-images.githubusercontent.com/19936679/110756480-8d046b80-824a-11eb-9b92-ce7dbd5f7adb.png)

**Comment by ocni-dtu** [comment]
Fixed on Compute
