### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by sanchitgulati** [procedural-build/ProceduralCS#5]
Downloaded the .gh file from [release](https://github.com/procedural-build/ProceduralCS/releases/tag/2020.8.0)

Made an account on [https://compute.procedural.build/](https://compute.procedural.build/)
Open the grasshopper with ComputeVWT-DEMO_v20200812.gh
Add Login details.
Step 0. Auth is success
Step 1. Fails at 'get or create project and task'
![issue](https://user-images.githubusercontent.com/2760236/92129148-6f6dc980-ee03-11ea-84e5-1513561c9ee0.jpg)

**Comment by ocni-dtu** [comment]
Hey @sanchitgulati, are you member of a company on Compute?

**Comment by sanchitgulati** [comment]
No, I am not. I don't see the option to add any company?

**Comment by ocni-dtu** [comment]
Having a company is mandatory for creating project, which again is mandatory from running any tasks.

You can't make a company from Grasshopper, that has to be done at: https://compute.procedural.build/
There should be a button called "Create Company" after you login 

You can't run any tasks as long as you don't have any credits on your company account. I can give you some credits to get started, but I need to know the name of the company you create
